apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: techtrends-prod
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    source:
      helm:
        valueFiles:
        - values-prod.yaml
    repoURL: https://github.com/Duclong115/TechTrends
    targetRevision: HEAD
  syncPolicy: {}
